#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <stdio.h>

#include "domlt.h"

// NOTE: this acts like set union (no duplicates allowed)
static intlist_t *intlist_insert_sorted(intlist_t *head, int num)
{
    intlist_t *current;

    // end of list?
    if (head == NULL || head->n >= num) { 
        intlist_t *node = (intlist_t *)malloc(sizeof(intlist_t));
        node->n = num;
        node->next = head;
        head = node;
    } else {
        // locate the node before the point of insertion
        current = head;
        while (current->next != NULL && current->next->n < num) {
            current = current->next;
        }
        if (current->n != num) {
            intlist_t *node = (intlist_t *)malloc(sizeof(intlist_t));
            node->n = num;
            node->next = current->next;
            current->next = node;
        }
    }
    return head;
}

void adjdigraph_make(adjdigraph_t *g, int numVerts, int r) {
    assert(numVerts > 0);
    assert(r >= 0 && r < numVerts);

    g->numVerts = numVerts;
    g->r = r;
    g->succ = (intlist_t **)malloc(numVerts * sizeof(intlist_t *));
    memset(g->succ, 0, numVerts * sizeof(intlist_t *));
}

void adjdigraph_insert_edge(adjdigraph_t *g, int v, int w) {
    assert(v >= 0 && v < g->numVerts);
    assert(w >= 0 && w < g->numVerts);

    g->succ[v] = intlist_insert_sorted(g->succ[v], w);
}

void adjdigraph_free(adjdigraph_t *g) {
    for (int i = 0; i < g->numVerts; i++) {
        intlist_t *hd = g->succ[i];
        while (hd != NULL) {
            intlist_t *hd_next = hd->next;
            free(hd);
            // iterate
            hd = hd_next;
        }
    }
    free(g->succ);
    g->r = 0;
    g->numVerts = 0;
    g->succ = NULL;
}


// FIXME: debug printing to something? svg?
void adjdigraph_dot(adjdigraph_t *g, FILE *fp) {
    intlist_t *nl;

    fprintf(fp, "digraph G\n{\n");
    for (int i = 0; i < g->numVerts; i++) {
        fprintf(fp, "    n%i [ shape = \"box\"\n"
                    "          fontname = \"Monospace\"\n"
                    "          label = \"", i);
        fprintf(fp, "%i\\l", i);
        fprintf(fp, "\" ];\n");
        
        nl = g->succ[i];
        while (nl != NULL) {
            fprintf(fp, "      n%i -> n%i;\n", 
                    i, nl->n);
            nl = nl->next;
        }
    }
    fprintf(fp, "}\n");
}

// Graph Dominators via Lengauer-Tarjan algorithm
//
// transcribed directly from the paper:
//
//   A Fast Algorithm for Finding Dominators in a Flowgraph
//

typedef struct state_s {
    // computed
    int         *parent;    // the vertex which is the parent of vertex w in the spanning tree generated by DFS
    intlist_t   **pred;     // predecessors
    int         *semi;      // ?
    int         *vertex;    // ?
    intlist_t   **buckets;  // a set of vertices whose semidominator is w
    int         *dom;       // the immediate dominator of w
    
    // computed, this is for path compression
    int         *ancestor;
    int         *label;
} state_t;

static void DFS(adjdigraph_t *g, state_t *state, int v, int *n) {
    int current_n = *n;
    *n = *n + 1;
    assert(current_n >= 0 && current_n < g->numVerts);
    state->semi[v] = current_n;
    state->vertex[current_n] = v;
    state->ancestor[v] = -1;
    // initialize variables for steps 2, 3 and 4
    intlist_t *hd = g->succ[v];
    while (hd != NULL) {
        int w = hd->n;
        if (state->semi[w] < 0) {
            state->parent[w] = v;
            DFS(g, state, w, n);
        }
        // add v to pred(w)
        state->pred[w] = intlist_insert_sorted(state->pred[w], v);

        // iterate
        hd = hd->next;
    }
}

static void Link(state_t *state, int v, int w) {
    state->ancestor[w] = v;
}

static void Compress(state_t *state, int v) {
    // this procedure assumes ancestor[v] >= 0
    if (state->ancestor[state->ancestor[v]] >= 0) {
        Compress(state, state->ancestor[v]);
        int a = state->ancestor[v];
        if (state->semi[state->label[a]] < state->semi[state->label[v]]) {
            state->label[v] = state->label[a];
        }
        state->ancestor[v] = state->ancestor[a];
    }
}

static int Eval(state_t *state, int v) {
    if (state->ancestor[v] < 0) {
        return v;
    } else {
        Compress(state, v);
        return state->label[v];
    }
}

// returns array of size g->numVerts
// the array d contains for each vertex v != r, d[v] = idom(v)
int *DominatorTree(adjdigraph_t *g) {
    state_t     state;
    int n;

    // FIXME: isn't this slightly wrong?
    // - label, semi should cover 0..n (inclusive)
    // - other arrays should cover 1..n (inclusive)
    // so?
    // where algorithm uses 0 as special value, we should use -1.
    // likewise with the bounds.

    // step 1
    // TODO: minimize memory allocations here
    state.dom = (int *)malloc(g->numVerts * sizeof(int));
    memset(state.dom, 0, g->numVerts * sizeof(int));

    state.pred = (intlist_t **)malloc(g->numVerts * sizeof(intlist_t *));
    memset(state.pred, 0, g->numVerts * sizeof(intlist_t *));

    state.semi = (int *)malloc(g->numVerts * sizeof(int));
    memset(state.semi, -1, g->numVerts * sizeof(int));

    state.vertex = (int *)malloc(g->numVerts * sizeof(int));
    memset(state.vertex, 0, g->numVerts * sizeof(int));

    state.parent = (int *)malloc(g->numVerts * sizeof(int));
    memset(state.parent, 0, g->numVerts * sizeof(int));

    state.buckets = (intlist_t **)malloc(g->numVerts * sizeof(intlist_t *));
    memset(state.buckets, 0, g->numVerts * sizeof(intlist_t *));

    state.ancestor = (int *)malloc(g->numVerts * sizeof(int));
    memset(state.ancestor, -1, g->numVerts * sizeof(int));

    state.label = (int *)malloc(g->numVerts * sizeof(int));
    for (int v = 0; v < g->numVerts; v++) {
        state.label[v] = v-1;
    }

    n = 0;
    DFS(g, &state, g->r, &n);
    state.label[0] = state.semi[0] = -1;

    // steps 2 and 3
    // initialize variables
    for (int i = n-1; i > 0; i--) {
        int w = state.vertex[i];

        // step 2
        intlist_t *hd_pred = state.pred[w];
        while (hd_pred != NULL) {
            int v = hd_pred->n;
            int u = Eval(&state, v);

            if (state.semi[u] < state.semi[w]) {
                state.semi[w] = state.semi[u];
            }
            // iterate
            hd_pred = hd_pred->next;
        }
        // add w to bucket[vertex[semi[w]]]
        int bucketNum = state.vertex[state.semi[w]];
        state.buckets[bucketNum] = intlist_insert_sorted(state.buckets[bucketNum], w);
        Link(&state, state.parent[w], w);

        // step 3
        int parent = state.parent[w];
        intlist_t *hd_bucket = state.buckets[parent];
        while (hd_bucket != NULL) {
            int v = hd_bucket->n;
            // delete v from buckets[parent]
            intlist_t *hd_bucket_next = hd_bucket->next;
            free(hd_bucket);

            int u = Eval(&state, v);
            state.dom[v] = state.semi[u] < state.semi[v] ? u : state.parent[w];

            // iterate
            hd_bucket = hd_bucket_next;
        }
        state.buckets[parent] = NULL;
    }

    // step 4
    for (int i = 1; i < n; i++) {
        int w = state.vertex[i];
        if (state.dom[w] != state.vertex[state.semi[w]]) {
            state.dom[w] = state.dom[state.dom[w]];
        }
    }
    state.dom[g->r] = -1;

    // deallocate
    for (int i = 0; i < g->numVerts; i++) {
        intlist_t *hd_pred = state.pred[i];
        while (hd_pred != NULL) {
            intlist_t *hd_pred_next = hd_pred->next;
            free(hd_pred);
            // iterate
            hd_pred = hd_pred_next;
        }
    }
    free(state.pred);
    free(state.semi);
    free(state.vertex);
    free(state.parent);
    free(state.buckets);
    free(state.ancestor);
    free(state.label);

    return state.dom;
}
